name: 'CI Job Launcher'
description: 'Launch a JEDI-CI job'
author: 'JCSDA'

inputs:
  container_version:
    description: 'Container version (latest, next)'
    required: true
    default: 'latest'
  target_project_name:
    description: 'Name build bundle project for this repository (if different from the repo name).'
    required: false
    default: ''
  jedi_ci_token:
    description: 'GitHub token associated with the JEDI CI GitHub app'
    required: false
    default: ''
  test_script:
    description: 'Test script to run (must be in //jedi-ci/shell/)'
    required: false
    default: 'run_tests.sh'
  target_repo_dir:
    description: 'Target repository directory'
    required: false
    default: 'target_repository'
  bundle_repository:
    description: 'Repository to use when cloning the bundle.'
    required: false
    default: 'https://github.com/JCSDA-internal/jedi-bundle.git'
  bundle_branch:
    description: 'Default branch to use when cloning the bundle.'
    required: false
    default: 'develop'
  unittest_tag:
    description: 'CMake tag used to execute unit tests.'
    required: false
    default: ''
  unittest_dependencies:
    description: '(Deprecated) use test_dependencies+test_strategy instead. This option forces test strategy to be ALL.'
    required: false
    default: ''
  test_dependencies:
    description: 'Build bundle dependencies used for tests.'
    required: false
    default: ''
  test_strategy:
    description: description: |
      The strategy used for building and running tests. May be ALL, INTEGRATION, or UNIT.
      - INTEGRATION: The bundle is trimmed to only include the test_dependencies all tests are run.
      - UNIT:        The bundle is trimmed to only include the test_dependencies and unit tests are run.
      - ALL:         A 2-stage build is performed with the first step using the
                     test_dependencies to build the unit tests and the second step
                     building the full bundle for integration tests.
    required: false
    default: ''
  self_test:
    description: 'Whether to run a self-test of the JEDI CI action.'
    required: false
    default: 'false'

# GITHUB_TOKEN: ${{ inputs.github_token }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    UNITTEST_TAG: ${{ inputs.unittest_tag }}
    CONTAINER_VERSION: ${{ inputs.container_version }}
    TARGET_PROJECT_NAME: ${{ inputs.target_project_name }}
    BUNDLE_BRANCH: ${{ inputs.bundle_branch }}
    TEST_SCRIPT: ${{ inputs.test_script }}
    TARGET_REPO_DIR: ${{ inputs.target_repo_dir }}
    BUNDLE_REPOSITORY: ${{ inputs.bundle_repository }}
    CI_SELF_TEST: ${{ inputs.self_test }}
    JEDI_CI_TOKEN: ${{ inputs.jedi_ci_token }}
    UNITTEST_DEPENDENCIES: ${{ inputs.unittest_dependencies }}
    TEST_DEPENDENCIES: ${{ inputs.test_dependencies }}
    TEST_STRATEGY: ${{ inputs.test_strategy }}

branding:
  icon: 'play'
  color: 'blue'
