# This dockerfile is used to build the base image for the JEDI-CI runner. The
# base image includes all dependencies required to install and launch
# the jedi-ci action library.

FROM python:3.11-alpine

# Install required packages
RUN apk add --no-cache \
    git

# Install Python build tools
RUN pip install --no-cache-dir \
    pip \
    setuptools \
    "requests>=2.32" \
    "PyJWT>=2.10" \
    "cryptography>=45.0" \
    "PyGithub>=2.6" \
    "boto3>=1.40" \
    "pyyaml>=6"
