name: Python Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Create venv
      run: |
        python -m venv venv
        source venv/bin/activate
        echo "VIRTUAL_ENV=${VIRTUAL_ENV}" >> $GITHUB_ENV

    - name: Install package
      run: |
        source ${VIRTUAL_ENV}/bin/activate
        python -m pip install --upgrade pip
        pip install -e .[test]

    - name: Run pytest
      run: |
        source ${VIRTUAL_ENV}/bin/activate
        pytest -v
